### ISSUE TITLE
Add support to android custom tel type

### ISSUE THREAD

**Issue by doshu** [fruux/sabre-vobject#315] opened 2016-04-12 08:25 UTC
is possible to add supports to the following item

TEL;X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A):54248464546

now the parser throw an exception because the format is unsupported

i have tried to modify the regexp that extract the params. now i can parse this string but the params are not recognized as tel type

**Comment by evert** [comment] 2016-04-12 09:39
* What software generates vCards that's that broken?
* Can you share the full vCard?

**Comment by doshu** [comment] 2016-04-12 09:43
the vcard has been created from android 6.0 on a galaxy s6 edge (the regular contact manager of samsung)

this is the full card

BEGIN:VCARD
VERSION:2.1
N:;test;;;
FN:test
X-ANDROID-CUSTOM:vnd.android.cursor.item/nickname;doshu;1;;;;;;;;;;;;;
TEL;CELL:3925714212
TEL;CALLBACK:35428456421
TEL;X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A):54248464546
IMPP;PREF=1:xmpp:alice@example.com
EMAIL;HOME:thomas.schiavello@gmail.com
EMAIL;X-person:23thomas@libero.it
ADR;HOME;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=76=69=61=20=63=61=76=61=67=6C=69=C3=A1=20=36;=62=69=65=6C=6C=61;=69=74=61=6C=69=61;=31=33=39=30=30;=69=74=61=6C=69=61
ADR;X-lavoro:;;via asd 106;lol;italia;13900;italia
ORG:inoma;it
TITLE:developer
NOTE:note
X-ANDROID-CUSTOM:vnd.android.cursor.item/contact_event;2016-04-09;1;;;;;;;;;;;;;
BDAY:--11-23
X-WHATSAPP:3925714212
X-SKYPE-USERNAME:doshu91
END:VCARD

**Comment by evert** [comment] 2016-04-12 09:47
That's interesting. I want to do a bit of digging to see if it's android who's at fault here. If it's their bug, I think you should first report a bug at the android project. But I'm not fully sure yet if this is wrong.

**Comment by doshu** [comment] 2016-04-12 09:49
do you think that X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A) is not a allowed format in vcard spec?


so, is normal that in the string TEL;CALLBACK:35428456421, CALLBACK is not recognized as TYPE but the parser creates a parameter called CALLBACK?

**Comment by evert** [comment] 2016-04-12 09:51
Hi Doshu,

I'm currently investigating. So I don't have definite answers yet.

    X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A)

Is definitely invalid for vCard 3 and 4, but not sure yet about 2.1.

> so, is normal that in the string TEL;CALLBACK:35428456421, CALLBACK is not recognized as TYPE but the parser creates a parameter called CALLBACK?

Yes, that absolutely is expected.

**Comment by evert** [comment] 2016-04-12 12:02
I took a look through the android source here:

https://android.googlesource.com/platform/frameworks/opt/vcard/+/master/java/com/android/vcard/VCardBuilder.java

and I don't really see any indication that it would spit out this type of data. I feel that the problem must be elsewhere.

However, I had another look at the vCard 2.1 spec, and reading that I find that it says custom properties and parameters can be specified as:

    any printable 7bit us-ascii except []=:.,

So that does imply that our regex is too strict for vCard 2.1, however, that line is still a broken line. You see, this line

     TEL;X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A):54248464546

The only correct interpretation is that that line starts a parameter with the name `X-CUSTOM(CHARSET`, which is ok. But then we need to continue parsing that parameter until we hit either a `;` (for the next parameter) or `:` for the end of the parameter list, but if we do that, the parameter value for `X-CUSTOM(CHARSET` is `UTF-8,ENCODING=QUOTED-PRINTABLE,=70=72=6F=76=61=20=70=65=72=73=6F=6E=61=6C=69=7A=7A)`, but as you can see, that value contains the `=` character many times, which is actually invalid, because not only parameter name, but also parameter values must be:

    any printable 7bit us-ascii except []=:.,

So if we follow the rules of vCard 2.1, we must reject this. If we bend the rules, I'm not sure what a correct interpretation is. My guess is that the `(` in the parameter name signifies a special parameter encoding, but this is some extension of the vCard 2.1 specification that I don't know, and I've never seen before.

And hence I'm doubtful Android encodes this. It seems more likely to me that something else created it, it got imported into an android phone (and the android parser is perhaps very lenient with broken data) and later on it got exported again.

Can you reproduce android exporting that vCard by creating a contact from scratch?

**Comment by doshu** [comment] 2016-04-12 12:23
i have created that vcard on my own with my samsung s6 edge with the standard contacts app

i have created another one now, a little semplified, with only one tel with a custom type

BEGIN:VCARD
VERSION:2.1
N:;test;;;
FN:test
TEL;X-CUSTOM(CHARSET=UTF-8,ENCODING=QUOTED-PRINTABLE,=74=68=69=73=20=69=73=20=61=20=63=75=73=74=6F=6D=20=74=79=70=65):3925714212
END:VCARD

**Comment by evert** [comment] 2016-04-12 12:24
What version of android is this?

**Comment by doshu** [comment] 2016-04-12 12:28
android 6.0.1 (samsung official)

build MMB29k.G925FXXU3DPBG

**Comment by evert** [comment] 2016-04-12 12:43
So yea, based on that, I'd say.. try opening a ticket in the android project. It's definitely an incorrect encoding. In the meantime you may want to try to export to vCard 3 or 4. vCard 3 has been released nearly 20 years ago, so still using vCard 2.1 has been a bad idea for almost 2 decades ;)

After you've opened the android ticket, feel free to paste the link to the ticket here. It will be interesting to see what they say. Perhaps it's worth even to create a workaround in sabre/vobject until they fix it, but it's pointless to do that before we get some feedback from them telling us _how_ that should be interpreted.

**Comment by doshu** [comment] 2016-04-14 06:20
this is the ticket in android project
https://code.google.com/p/android/issues/detail?id=206603&sort=-opened&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&start=100

i don't think we will recieve responses in a shor time

**Comment by evert** [comment] 2016-04-14 11:44
I hope you're wrong! Lets wait a bit and see. In the meantime, have you found an option to export as vCard 4 or 3?

**Comment by doshu** [comment] 2016-04-14 12:08
no, there is not a standard way for exporting in vcard 3 or 4. 
exporting with external app, loose the custom field

**Comment by evert** [comment] 2016-10-10 18:51
I'm going to close this on the notion that we haven't figure out:

1. The source of the issue
2. What the intended way is this property _should_ have been parsed.

I'm not necessarily against accepting a patch that can deal with this (maybe even using an optional flag), but it's not a priority for me personally, therefore I think it's better for me to just close the issue instead of giving off the impression that I'll get to this later.

**Closed by evert** 2016-10-10 18:51 UTC
Labels: bug, version-4.x
