### ISSUE TITLE
Add VALUE=URL param during validation of PHOTO URL properties

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-vobject#235] opened 2015-06-30 12:20 UTC
OS X Addressbook.app on 10.8 aborts the sync once it hits a vCard with a `PHOTO:http://example.org/photo.jpg` property with the following error:

```
CardDAVPlugin-ERROR -_handleAddsOrModifies: exception processing addsOrModifies The value for 'scheme' should be non-nil and non-empty.
```

The only way to fix this, is to remove the PHOTO property entirely from the card or add a `VALUE=URL` param to it.

OS X 10.7 as well as 10.9 and up are unaffected by this bug (reported at Apple as <rdar://problem/21609706>).

Although this param is [not required](https://tools.ietf.org/html/rfc6350#section-6.2.4), is it worth to add this to the repair tool since 10.8 Addressbook.app is still a popular CardDAV client?

**Comment by evert** [comment] 2015-07-03 22:30
Is this a duplicate of #227 ?

**Comment by evert** [comment] 2015-07-03 22:58
So yea.. I'm happy to add this workaround... Basically what I want to do is simply *always* add `VALUE=URL` for a property, even if the default value type is already `URL`

**Closed** 2015-11-26 03:06 UTC
Labels: enhancement, question, version-4.x
